### ISSUE TITLE
Features in the PubMed dataset

### ISSUE THREAD

**Issue by contrachako** [Nanyuu/TUA#2]
Hi Nanyuu!
I am interested in detailed points in your experiments using the benchmark dataset.
In your paper, you define the feature matrix as X \in {0, 1}^{N \times d}; however, the PubMed dataset seems to have continuous-valued features.
When experimenting with PubMed, in Algorithm 1, do the elements of the original X remain continuous values, and only the elements of X_{Fake} are {0, 1}?
If not, are you binarizing the PubMed features somewhere in the code?

**Comment by Nanyuu** [comment]
Hi contrachako！
For the PubMed, the features of original nodes remain continuous. And, in the experiment, the fake features are set to {0,1}.
We notice that the declaration of feature matrix (X) and the benchmark dataset (PubMed) unmatched in the paper. This problem will be fixed. Thanks for pointing out it!

**Comment by contrachako** [comment]
Nanyuu, thank you for your reply.
I look forward to your future updates and results on the PubMed dataset!
